import { Manager, Vehicle, UraAreaBoundary } from './types';

export const MANAGERS: Manager[] = [
  {
    id: 'mgr-1',
    name: 'Tan Wei Ming',
    role: 'Senior Dispatch Manager',
    assignedFleetName: 'Fleet A (Central & South)',
    focusRegion: 'Central & Southern Singapore',
    phone: '+65 9182 3341',
  },
  {
    id: 'mgr-2',
    name: 'Priya Nair',
    role: 'Operations Dispatch Lead',
    assignedFleetName: 'Fleet B (East & North-East)',
    focusRegion: 'East & North-East Singapore',
    phone: '+65 8421 9904',
  },
  {
    id: 'mgr-3',
    name: 'Marcus Lim',
    role: 'Fleet Logistics Controller',
    assignedFleetName: 'Fleet C (West & North)',
    focusRegion: 'West & Northern Singapore',
    phone: '+65 9632 7715',
  },
];

// 30 Vehicles total (10 per manager, minimum 1 delivery each, each row having real invented values)
export const INITIAL_VEHICLES: Vehicle[] = [
  // ==========================================
  // MANAGER 1: Tan Wei Ming (Central & South) - 10 Vehicles
  // ==========================================
  {
    id: 'veh-01',
    managerId: 'mgr-1',
    carPlate: 'SGB 4821 K',
    driverName: 'Muhammad Fadzil',
    driverContact: '+65 9123 4567',
    uraArea: 'Downtown Core',
    gpsLocation: { x: 550, y: 440, lat: 1.2838, lng: 103.8591 },
    deliveries: [
      {
        id: 'del-01-01',
        item: 'Medical Diagnostic Kits (Refrigerated)',
        pickupLocation: 'Singapore General Hospital Logistics Hub',
        dropoffLocation: 'Marina One West Tower Level 14',
        pickupUra: 'Bukit Merah',
        dropoffUra: 'Downtown Core',
        estimatedTime: '13:45 - 14:15',
        estimatedDistance: '4.8 km',
        status: 'delayed',
        isDelayed: true,
        isInTransit: true,
        sequence: 1,
        notes: 'Heavy traffic congestion along Shenton Way due to lane closure.',
      },
      {
        id: 'del-01-02',
        item: 'Corporate Audit Documents (Confidential)',
        pickupLocation: 'Ocean Financial Centre Level 21',
        dropoffLocation: 'Suntec City Tower 3 Loading Bay',
        pickupUra: 'Downtown Core',
        dropoffUra: 'Downtown Core',
        estimatedTime: '14:45 - 15:15',
        estimatedDistance: '2.6 km',
        status: 'scheduled',
        isDelayed: true, // will be delayed if subsequent
        sequence: 2,
        notes: 'Follow-up delivery at risk of delay due to initial delay.',
      },
      {
        id: 'del-01-03',
        item: 'High-End Retail Apparel (4 Cartons)',
        pickupLocation: 'Raffles City Shopping Centre',
        dropoffLocation: 'Ion Orchard Basement 2 Concierge',
        pickupUra: 'Downtown Core',
        dropoffUra: 'Orchard',
        estimatedTime: '15:45 - 16:15',
        estimatedDistance: '3.9 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 3,
      },
    ],
  },
  {
    id: 'veh-02',
    managerId: 'mgr-1',
    carPlate: 'SLA 1932 P',
    driverName: 'Lim Kok Seng',
    driverContact: '+65 8234 5678',
    uraArea: 'Bukit Merah',
    gpsLocation: { x: 510, y: 450, lat: 1.2819, lng: 103.8239 },
    deliveries: [
      {
        id: 'del-02-01',
        item: 'Specialty Coffee Beans (60 kg)',
        pickupLocation: 'Tiong Bahru Industrial Estate Block 10',
        dropoffLocation: 'Great World City Cafe Unit #01-12',
        pickupUra: 'Bukit Merah',
        dropoffUra: 'River Valley',
        estimatedTime: '14:00 - 14:30',
        estimatedDistance: '3.2 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-02-02',
        item: 'Architectural Sample Swatches',
        pickupLocation: 'Henderson Building Loading Bay 2',
        dropoffLocation: 'Mapletree Business City Tower A',
        pickupUra: 'Bukit Merah',
        dropoffUra: 'Queenstown',
        estimatedTime: '15:15 - 15:45',
        estimatedDistance: '4.5 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
      {
        id: 'del-02-03',
        item: 'Ergonomic Office Equipment',
        pickupLocation: 'Alexandra Technopark Block B',
        dropoffLocation: 'HarbourFront Centre Office Lobby',
        pickupUra: 'Bukit Merah',
        dropoffUra: 'Bukit Merah',
        estimatedTime: '16:15 - 16:45',
        estimatedDistance: '3.8 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 3,
      },
    ],
  },
  {
    id: 'veh-03',
    managerId: 'mgr-1',
    carPlate: 'GBF 8294 D',
    driverName: 'Karthik Subramaniam',
    driverContact: '+65 9345 6789',
    uraArea: 'Queenstown',
    gpsLocation: { x: 470, y: 430, lat: 1.2942, lng: 103.7861 },
    deliveries: [
      {
        id: 'del-03-01',
        item: 'Semiconductor Testing Wafers',
        pickupLocation: 'Science Park II The Galen',
        dropoffLocation: 'Biopolis Epicentre Loading Deck',
        pickupUra: 'Queenstown',
        dropoffUra: 'Queenstown',
        estimatedTime: '13:30 - 14:00',
        estimatedDistance: '3.5 km',
        status: 'delayed',
        isDelayed: true,
        isInTransit: true,
        sequence: 1,
        notes: 'Access gate security clearance delay at loading dock.',
      },
      {
        id: 'del-03-02',
        item: 'Lab Cleanroom Consumables',
        pickupLocation: 'One-North Fusionopolis Way',
        dropoffLocation: 'National University Hospital Pharmacy',
        pickupUra: 'Queenstown',
        dropoffUra: 'Queenstown',
        estimatedTime: '14:30 - 15:00',
        estimatedDistance: '2.8 km',
        status: 'scheduled',
        isDelayed: true,
        sequence: 2,
        notes: 'Potential cascade delay from preceding BioPolis pickup.',
      },
    ],
  },
  {
    id: 'veh-04',
    managerId: 'mgr-1',
    carPlate: 'GBE 5102 Z',
    driverName: 'Ang Chee Keong',
    driverContact: '+65 8456 7890',
    uraArea: 'Tanglin',
    gpsLocation: { x: 490, y: 395, lat: 1.3060, lng: 103.8125 },
    deliveries: [
      {
        id: 'del-04-01',
        item: 'Diplomatic Embassy Pouches',
        pickupLocation: 'Nassim Road Embassy Dispatch Point',
        dropoffLocation: 'Ministry of Foreign Affairs Protocol',
        pickupUra: 'Tanglin',
        dropoffUra: 'Tanglin',
        estimatedTime: '14:15 - 14:45',
        estimatedDistance: '2.1 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-04-02',
        item: 'Fine Art Gallery Catalogues',
        pickupLocation: 'Dempsey Hill Gallery Cluster Blk 9',
        dropoffLocation: 'Orchard Boulevard Private Gallery',
        pickupUra: 'Tanglin',
        dropoffUra: 'Orchard',
        estimatedTime: '15:30 - 16:00',
        estimatedDistance: '3.4 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-05',
    managerId: 'mgr-1',
    carPlate: 'SKV 9912 A',
    driverName: 'Nurul Huda bte Ahmad',
    driverContact: '+65 9567 8901',
    uraArea: 'Novena',
    gpsLocation: { x: 535, y: 360, lat: 1.3204, lng: 103.8436 },
    deliveries: [
      {
        id: 'del-05-01',
        item: 'Ophthalmic Surgical Lenses',
        pickupLocation: 'Novena Specialist Center Level 8',
        dropoffLocation: 'Tan Tock Seng Hospital Central Stores',
        pickupUra: 'Novena',
        dropoffUra: 'Novena',
        estimatedTime: '14:00 - 14:20',
        estimatedDistance: '1.2 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-05-02',
        item: 'Dental Orthodontic Appliances',
        pickupLocation: 'Thomson Road Medical Hub',
        dropoffLocation: 'Balestier Dental Surgery',
        pickupUra: 'Novena',
        dropoffUra: 'Novena',
        estimatedTime: '15:00 - 15:30',
        estimatedDistance: '2.5 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-06',
    managerId: 'mgr-1',
    carPlate: 'GBC 3481 T',
    driverName: 'David Lee Chun Kit',
    driverContact: '+65 8678 9012',
    uraArea: 'Toa Payoh',
    gpsLocation: { x: 550, y: 325, lat: 1.3343, lng: 103.8563 },
    deliveries: [
      {
        id: 'del-06-01',
        item: 'Commercial Print Run Catalogues',
        pickupLocation: 'Toa Payoh Industrial Park Lorong 8',
        dropoffLocation: 'HDB Hub Atrium Event Counter',
        pickupUra: 'Toa Payoh',
        dropoffUra: 'Toa Payoh',
        estimatedTime: '14:10 - 14:40',
        estimatedDistance: '2.4 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-06-02',
        item: 'Educational Testing Materials',
        pickupLocation: 'Lorong 1 Community Educational Centre',
        dropoffLocation: 'Caldecott Broadcasting Centre Archive',
        pickupUra: 'Toa Payoh',
        dropoffUra: 'Novena',
        estimatedTime: '15:15 - 15:45',
        estimatedDistance: '3.6 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
      {
        id: 'del-06-03',
        item: 'Eco-Packaging Biodegradable Bags',
        pickupLocation: 'Braddell Tech Commercial Complex',
        dropoffLocation: 'Bishan Junction 8 Supermarket Bay',
        pickupUra: 'Toa Payoh',
        dropoffUra: 'Bishan',
        estimatedTime: '16:30 - 17:00',
        estimatedDistance: '4.1 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 3,
      },
    ],
  },
  {
    id: 'veh-07',
    managerId: 'mgr-1',
    carPlate: 'SLA 4409 U',
    driverName: 'Ramesh Kumar',
    driverContact: '+65 9789 0123',
    uraArea: 'Kallang',
    gpsLocation: { x: 585, y: 380, lat: 1.3115, lng: 103.8631 },
    deliveries: [
      {
        id: 'del-07-01',
        item: 'Sports Stadium Broadcasting Equipment',
        pickupLocation: 'Kallang Distripark Block 1',
        dropoffLocation: 'Singapore National Stadium Gate 4',
        pickupUra: 'Kallang',
        dropoffUra: 'Kallang',
        estimatedTime: '14:20 - 14:50',
        estimatedDistance: '3.0 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-07-02',
        item: 'Event Signage and Backdrop Stands',
        pickupLocation: 'Kallang Wave Mall Logistics Zone',
        dropoffLocation: 'Marina Bay Sands Expo Hall B',
        pickupUra: 'Kallang',
        dropoffUra: 'Downtown Core',
        estimatedTime: '15:40 - 16:10',
        estimatedDistance: '4.6 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-08',
    managerId: 'mgr-1',
    carPlate: 'GBG 7183 E',
    driverName: 'Tan Beng Huat',
    driverContact: '+65 8890 1234',
    uraArea: 'Bishan',
    gpsLocation: { x: 540, y: 290, lat: 1.3508, lng: 103.8488 },
    deliveries: [
      {
        id: 'del-08-01',
        item: 'Robotics Educational Kits (12 sets)',
        pickupLocation: 'Bishan Place Tech Incubator',
        dropoffLocation: 'Raffles Institution Science Block',
        pickupUra: 'Bishan',
        dropoffUra: 'Bishan',
        estimatedTime: '14:05 - 14:35',
        estimatedDistance: '2.1 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
    ],
  },
  {
    id: 'veh-09',
    managerId: 'mgr-1',
    carPlate: 'SKT 2291 R',
    driverName: 'Chloe Seah Ling',
    driverContact: '+65 9901 2345',
    uraArea: 'Bukit Timah',
    gpsLocation: { x: 470, y: 350, lat: 1.3329, lng: 103.7744 },
    deliveries: [
      {
        id: 'del-09-01',
        item: 'Organic Nursery Planters & Saplings',
        pickupLocation: 'Sixth Avenue Horticulture Hub',
        dropoffLocation: 'King Albert Park Residences Service Gate',
        pickupUra: 'Bukit Timah',
        dropoffUra: 'Bukit Timah',
        estimatedTime: '14:15 - 14:45',
        estimatedDistance: '2.7 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-09-02',
        item: 'Veterinary Vaccine Ampoules',
        pickupLocation: 'Upper Bukit Timah Veterinary Hospital',
        dropoffLocation: 'Coronation Plaza Animal Care',
        pickupUra: 'Bukit Timah',
        dropoffUra: 'Bukit Timah',
        estimatedTime: '15:20 - 15:50',
        estimatedDistance: '4.2 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-10',
    managerId: 'mgr-1',
    carPlate: 'SGB 6128 M',
    driverName: 'Firdaus bin Osman',
    driverContact: '+65 8012 3456',
    uraArea: 'Marine Parade',
    gpsLocation: { x: 640, y: 420, lat: 1.3023, lng: 103.9073 },
    deliveries: [
      {
        id: 'del-10-01',
        item: 'Artisan Sourdough & Pastry Batches',
        pickupLocation: 'Katong Antique Bakerhouse',
        dropoffLocation: 'Parkway Parade Level 1 Gourmet Pantry',
        pickupUra: 'Marine Parade',
        dropoffUra: 'Marine Parade',
        estimatedTime: '13:50 - 14:15',
        estimatedDistance: '1.8 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-10-02',
        item: 'Boutique Resort Bath Amenities',
        pickupLocation: 'East Coast Road Distribution Depot',
        dropoffLocation: 'East Coast Park Chalet Admin Office',
        pickupUra: 'Marine Parade',
        dropoffUra: 'Marine Parade',
        estimatedTime: '15:00 - 15:30',
        estimatedDistance: '3.6 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },

  // ==========================================
  // MANAGER 2: Priya Nair (East & North-East) - 10 Vehicles
  // ==========================================
  {
    id: 'veh-11',
    managerId: 'mgr-2',
    carPlate: 'SKL 7731 B',
    driverName: 'Hafiz bin Rosli',
    driverContact: '+65 9112 3344',
    uraArea: 'Tampines',
    gpsLocation: { x: 740, y: 320, lat: 1.3532, lng: 103.9452 },
    deliveries: [
      {
        id: 'del-11-01',
        item: 'Aviation Avionics Spare Connectors',
        pickupLocation: 'Changi North Industrial Estate St 1',
        dropoffLocation: 'Tampines Telepark Data Centre Bay 2',
        pickupUra: 'Changi',
        dropoffUra: 'Tampines',
        estimatedTime: '13:30 - 14:00',
        estimatedDistance: '7.8 km',
        status: 'delayed',
        isDelayed: true,
        isInTransit: true,
        sequence: 1,
        notes: 'Expressway PIE clearance bottleneck at Tampines Ave 5 exit.',
      },
      {
        id: 'del-11-02',
        item: 'Consumer Smart Electronics (20 Units)',
        pickupLocation: 'Tampines Logistics Park Block 7',
        dropoffLocation: 'Century Square Retail Unit #03-22',
        pickupUra: 'Tampines',
        dropoffUra: 'Tampines',
        estimatedTime: '14:30 - 15:00',
        estimatedDistance: '3.2 km',
        status: 'scheduled',
        isDelayed: true,
        sequence: 2,
        notes: 'At risk of cascading delay due to PIE bottleneck.',
      },
      {
        id: 'del-11-03',
        item: 'Household Appliance Replacement Motors',
        pickupLocation: 'Tampines Industrial Avenue 4',
        dropoffLocation: 'Pasir Ris West Plaza Workshop',
        pickupUra: 'Tampines',
        dropoffUra: 'Pasir Ris',
        estimatedTime: '15:45 - 16:15',
        estimatedDistance: '5.1 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 3,
      },
    ],
  },
  {
    id: 'veh-12',
    managerId: 'mgr-2',
    carPlate: 'SLA 8832 C',
    driverName: 'Brandon Tay Wei Lun',
    driverContact: '+65 8223 4455',
    uraArea: 'Bedok',
    gpsLocation: { x: 680, y: 370, lat: 1.3236, lng: 103.9273 },
    deliveries: [
      {
        id: 'del-12-01',
        item: 'Bakery Supply Yeast & Specialty Flour',
        pickupLocation: 'Bedok Industrial Park E Block 3014',
        dropoffLocation: 'Bedok Mall Loading Dock B1',
        pickupUra: 'Bedok',
        dropoffUra: 'Bedok',
        estimatedTime: '14:00 - 14:30',
        estimatedDistance: '2.5 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-12-02',
        item: 'Commercial Water Purification Cartridges',
        pickupLocation: 'Kaki Bukit Industrial Terrace',
        dropoffLocation: 'Chai Chee Technopark Level 4',
        pickupUra: 'Bedok',
        dropoffUra: 'Bedok',
        estimatedTime: '15:00 - 15:30',
        estimatedDistance: '3.7 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-13',
    managerId: 'mgr-2',
    carPlate: 'GBF 6610 H',
    driverName: 'Siti Nurhaliza bte Yusof',
    driverContact: '+65 9334 5566',
    uraArea: 'Changi',
    gpsLocation: { x: 820, y: 350, lat: 1.3564, lng: 103.9870 },
    deliveries: [
      {
        id: 'del-13-01',
        item: 'Air Cargo Express Customs Clearance Docs',
        pickupLocation: 'Changi Airfreight Centre Building C',
        dropoffLocation: 'Changi Airport Terminal 3 Baggage Service',
        pickupUra: 'Changi',
        dropoffUra: 'Changi',
        estimatedTime: '13:50 - 14:15',
        estimatedDistance: '3.6 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-13-02',
        item: 'Perishable Gourmet Seafood (Cold Box)',
        pickupLocation: 'Changi South Logistics Hub Bay 8',
        dropoffLocation: 'Jewel Changi Basement Seafood Market',
        pickupUra: 'Changi',
        dropoffUra: 'Changi',
        estimatedTime: '14:45 - 15:15',
        estimatedDistance: '4.2 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-14',
    managerId: 'mgr-2',
    carPlate: 'GBE 3901 J',
    driverName: 'Manojkumar Pillai',
    driverContact: '+65 8445 6677',
    uraArea: 'Pasir Ris',
    gpsLocation: { x: 745, y: 260, lat: 1.3721, lng: 103.9474 },
    deliveries: [
      {
        id: 'del-14-01',
        item: 'Resort Water Sports Maintenance Gear',
        pickupLocation: 'Loyang Offshore Supply Base Wharf 3',
        dropoffLocation: 'Downtown East D\'Resort Concierge',
        pickupUra: 'Pasir Ris',
        dropoffUra: 'Pasir Ris',
        estimatedTime: '14:15 - 14:45',
        estimatedDistance: '4.1 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-14-02',
        item: 'Aquarium Marine Life Supplies',
        pickupLocation: 'Pasir Ris Farmway 2 Hatchery',
        dropoffLocation: 'White Sands Shopping Centre Unit #02-18',
        pickupUra: 'Pasir Ris',
        dropoffUra: 'Pasir Ris',
        estimatedTime: '15:30 - 16:00',
        estimatedDistance: '3.8 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-15',
    managerId: 'mgr-2',
    carPlate: 'SKW 1294 K',
    driverName: 'Jason Ong Boon Kiat',
    driverContact: '+65 9556 7788',
    uraArea: 'Punggol',
    gpsLocation: { x: 670, y: 200, lat: 1.4052, lng: 103.9023 },
    deliveries: [
      {
        id: 'del-15-01',
        item: 'Eco-Smart Residential Solar Inverters',
        pickupLocation: 'Punggol Digital District Project Office',
        dropoffLocation: 'Waterway Point West Wing Loading Bay',
        pickupUra: 'Punggol',
        dropoffUra: 'Punggol',
        estimatedTime: '13:40 - 14:10',
        estimatedDistance: '2.4 km',
        status: 'delayed',
        isDelayed: true,
        isInTransit: true,
        sequence: 1,
        notes: 'Unloading ramp blocked by external concrete mixer.',
      },
      {
        id: 'del-15-02',
        item: 'High-Density Server Fiber Optic Patch Cables',
        pickupLocation: 'Punggol Northshore Commercial Hub',
        dropoffLocation: 'Sengkang Grand Mall Basement IT Room',
        pickupUra: 'Punggol',
        dropoffUra: 'Sengkang',
        estimatedTime: '14:40 - 15:10',
        estimatedDistance: '4.9 km',
        status: 'scheduled',
        isDelayed: true,
        sequence: 2,
        notes: 'Delayed if vehicle delayed at Waterway Point.',
      },
    ],
  },
  {
    id: 'veh-16',
    managerId: 'mgr-2',
    carPlate: 'GBC 8192 L',
    driverName: 'Sanjay Krishnan',
    driverContact: '+65 8667 8899',
    uraArea: 'Sengkang',
    gpsLocation: { x: 650, y: 245, lat: 1.3916, lng: 103.8953 },
    deliveries: [
      {
        id: 'del-16-01',
        item: 'Hospital Sterile Surgical Drapes',
        pickupLocation: 'Fernvale Street Depot Unit 3',
        dropoffLocation: 'Sengkang General Hospital Pharmacy Receiving',
        pickupUra: 'Sengkang',
        dropoffUra: 'Sengkang',
        estimatedTime: '14:10 - 14:35',
        estimatedDistance: '2.6 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-16-02',
        item: 'Orthopedic Support Braces & Splints',
        pickupLocation: 'Anchorvale Lane Medical Stores',
        dropoffLocation: 'Compass One Medical Clinic #02-15',
        pickupUra: 'Sengkang',
        dropoffUra: 'Sengkang',
        estimatedTime: '15:15 - 15:45',
        estimatedDistance: '3.1 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
      {
        id: 'del-16-03',
        item: 'Veterinary Nutritional Pastes',
        pickupLocation: 'Rivervale Plaza Service Bay',
        dropoffLocation: 'Sengkang West Way Pet Haven Clinic',
        pickupUra: 'Sengkang',
        dropoffUra: 'Sengkang',
        estimatedTime: '16:15 - 16:45',
        estimatedDistance: '2.8 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 3,
      },
    ],
  },
  {
    id: 'veh-17',
    managerId: 'mgr-2',
    carPlate: 'SLA 5590 M',
    driverName: 'Teo Zhi Wei',
    driverContact: '+65 9778 9900',
    uraArea: 'Hougang',
    gpsLocation: { x: 625, y: 280, lat: 1.3708, lng: 103.8920 },
    deliveries: [
      {
        id: 'del-17-01',
        item: 'Textile Printing Dyes & Fabric Rolls',
        pickupLocation: 'Defu Industrial Park Lane 10 Block 22',
        dropoffLocation: 'Hougang Mall Customer Service Bay',
        pickupUra: 'Hougang',
        dropoffUra: 'Hougang',
        estimatedTime: '14:20 - 14:50',
        estimatedDistance: '3.4 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
    ],
  },
  {
    id: 'veh-18',
    managerId: 'mgr-2',
    carPlate: 'GBF 1944 N',
    driverName: 'Muhammad Zulkifli',
    driverContact: '+65 8889 0011',
    uraArea: 'Ang Mo Kio',
    gpsLocation: { x: 575, y: 260, lat: 1.3691, lng: 103.8454 },
    deliveries: [
      {
        id: 'del-18-01',
        item: 'Precision Machined Metal Fasteners',
        pickupLocation: 'Ang Mo Kio Industrial Park 2 Block 5032',
        dropoffLocation: 'AMK Hub Loading Ramp Bay 1',
        pickupUra: 'Ang Mo Kio',
        dropoffUra: 'Ang Mo Kio',
        estimatedTime: '14:00 - 14:30',
        estimatedDistance: '2.9 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-18-02',
        item: 'Electronics Soldering Stations & Flux',
        pickupLocation: 'Techplace II Street 65',
        dropoffLocation: 'Yio Chu Kang Road Assembly Plant',
        pickupUra: 'Ang Mo Kio',
        dropoffUra: 'Ang Mo Kio',
        estimatedTime: '15:10 - 15:40',
        estimatedDistance: '3.7 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-19',
    managerId: 'mgr-2',
    carPlate: 'SKU 8021 P',
    driverName: 'Jonathan Tan Wei Ren',
    driverContact: '+65 9990 1122',
    uraArea: 'Serangoon',
    gpsLocation: { x: 605, y: 315, lat: 1.3554, lng: 103.8679 },
    deliveries: [
      {
        id: 'del-19-01',
        item: 'Commercial Kitchen Refrigeration Gas',
        pickupLocation: 'Serangoon North Industrial Estate St 4',
        dropoffLocation: 'NEX Shopping Centre B2 Loading Zone',
        pickupUra: 'Serangoon',
        dropoffUra: 'Serangoon',
        estimatedTime: '14:05 - 14:35',
        estimatedDistance: '3.5 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-19-02',
        item: 'Specialty French Wine Wooden Crates (x6)',
        pickupLocation: 'Lorong Chuan Wine Cellar Depot',
        dropoffLocation: 'Serangoon Gardens Country Club Pantry',
        pickupUra: 'Serangoon',
        dropoffUra: 'Serangoon',
        estimatedTime: '15:20 - 15:50',
        estimatedDistance: '3.1 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-20',
    managerId: 'mgr-2',
    carPlate: 'SGB 9033 Q',
    driverName: 'Eileen Koh Min',
    driverContact: '+65 8001 2233',
    uraArea: 'Paya Lebar',
    gpsLocation: { x: 630, y: 350, lat: 1.3400, lng: 103.8900 },
    deliveries: [
      {
        id: 'del-20-01',
        item: 'Telecom Fiber Splicing Kits',
        pickupLocation: 'Paya Lebar Square Logistics Area',
        dropoffLocation: 'Paya Lebar Airbase Gate 3 Dispatch',
        pickupUra: 'Paya Lebar',
        dropoffUra: 'Paya Lebar',
        estimatedTime: '14:15 - 14:45',
        estimatedDistance: '3.9 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
    ],
  },

  // ==========================================
  // MANAGER 3: Marcus Lim (West & North) - 10 Vehicles
  // ==========================================
  {
    id: 'veh-21',
    managerId: 'mgr-3',
    carPlate: 'GBF 4912 R',
    driverName: 'Ahmad Daniel bin Razak',
    driverContact: '+65 9111 2233',
    uraArea: 'Jurong East',
    gpsLocation: { x: 370, y: 400, lat: 1.3329, lng: 103.7436 },
    deliveries: [
      {
        id: 'del-21-01',
        item: 'Industrial Hydraulic Hoses & Seals',
        pickupLocation: 'Jurong Port Road Logistics Hub',
        dropoffLocation: 'International Business Park Tower 2',
        pickupUra: 'Jurong East',
        dropoffUra: 'Jurong East',
        estimatedTime: '13:20 - 13:50',
        estimatedDistance: '5.2 km',
        status: 'delayed',
        isDelayed: true,
        isInTransit: true,
        sequence: 1,
        notes: 'Tire puncture replaced on AYE expressway shoulder.',
      },
      {
        id: 'del-21-02',
        item: 'Heavy Machinery Sensor Modules',
        pickupLocation: 'Toh Guan Road East Warehouse #04-10',
        dropoffLocation: 'JEM Commercial Loading Bay B2',
        pickupUra: 'Jurong East',
        dropoffUra: 'Jurong East',
        estimatedTime: '14:30 - 15:00',
        estimatedDistance: '2.8 km',
        status: 'scheduled',
        isDelayed: true,
        sequence: 2,
        notes: 'Subsequent schedule impacted by tire maintenance delay.',
      },
      {
        id: 'del-21-03',
        item: 'Medical Orthopedic Implants',
        pickupLocation: 'Jurong Gateway Road Medical Suite',
        dropoffLocation: 'Ng Teng Fong General Hospital Stores',
        pickupUra: 'Jurong East',
        dropoffUra: 'Jurong East',
        estimatedTime: '15:30 - 16:00',
        estimatedDistance: '1.5 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 3,
      },
    ],
  },
  {
    id: 'veh-22',
    managerId: 'mgr-3',
    carPlate: 'SLA 3110 S',
    driverName: 'Goh Wei Liang',
    driverContact: '+65 8222 3344',
    uraArea: 'Jurong West',
    gpsLocation: { x: 280, y: 390, lat: 1.3404, lng: 103.7090 },
    deliveries: [
      {
        id: 'del-22-01',
        item: 'Polymer Engineering Granules (200 kg)',
        pickupLocation: 'Jalan Boon Lay Chemical Hub',
        dropoffLocation: 'Jurong Island Checkpoint Cargo Office',
        pickupUra: 'Jurong West',
        dropoffUra: 'Western Islands',
        estimatedTime: '14:00 - 14:40',
        estimatedDistance: '8.4 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-22-02',
        item: 'Lab Analytical Reagent Solvents',
        pickupLocation: 'Nanyang Technological University North Spine',
        dropoffLocation: 'Jurong Point Mall Pharmacy Bay',
        pickupUra: 'Jurong West',
        dropoffUra: 'Jurong West',
        estimatedTime: '15:15 - 15:45',
        estimatedDistance: '4.6 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-23',
    managerId: 'mgr-3',
    carPlate: 'GBE 9221 T',
    driverName: 'Suresh Narayanan',
    driverContact: '+65 9333 4455',
    uraArea: 'Tuas',
    gpsLocation: { x: 170, y: 440, lat: 1.3210, lng: 103.6420 },
    deliveries: [
      {
        id: 'del-23-01',
        item: 'Marine Engine Gaskets & Impellers',
        pickupLocation: 'Tuas South Boulevard Shipyard 5',
        dropoffLocation: 'Tuas Mega Port Terminal 1 Gate 8',
        pickupUra: 'Tuas',
        dropoffUra: 'Tuas',
        estimatedTime: '14:10 - 14:45',
        estimatedDistance: '6.7 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-23-02',
        item: 'Corrosion-Resistant Stainless Steel Valves',
        pickupLocation: 'Tuas Avenue 11 Factory 4',
        dropoffLocation: 'Tuas West Road Warehouse Complex',
        pickupUra: 'Tuas',
        dropoffUra: 'Tuas',
        estimatedTime: '15:15 - 15:45',
        estimatedDistance: '3.9 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-24',
    managerId: 'mgr-3',
    carPlate: 'SKV 6743 U',
    driverName: 'Melvin Chong',
    driverContact: '+65 8444 5566',
    uraArea: 'Woodlands',
    gpsLocation: { x: 440, y: 150, lat: 1.4382, lng: 103.7890 },
    deliveries: [
      {
        id: 'del-24-01',
        item: 'Cross-Border Semiconductor Components',
        pickupLocation: 'Woodlands Checkpoint Cargo Clearance Deck',
        dropoffLocation: 'Woodlands Industrial Park E5 Block 10',
        pickupUra: 'Woodlands',
        dropoffUra: 'Woodlands',
        estimatedTime: '13:40 - 14:15',
        estimatedDistance: '4.3 km',
        status: 'delayed',
        isDelayed: true,
        isInTransit: true,
        sequence: 1,
        notes: 'Customs security scanning queue backlog at Causeway.',
      },
      {
        id: 'del-24-02',
        item: 'Precision Optics Assembly Frames',
        pickupLocation: 'Woodlands North Coast Tech Hub',
        dropoffLocation: 'Causeway Point Basement Logistics Dock',
        pickupUra: 'Woodlands',
        dropoffUra: 'Woodlands',
        estimatedTime: '14:45 - 15:15',
        estimatedDistance: '3.5 km',
        status: 'scheduled',
        isDelayed: true,
        sequence: 2,
        notes: 'Potential cascade delay from border customs clearance.',
      },
    ],
  },
  {
    id: 'veh-25',
    managerId: 'mgr-3',
    carPlate: 'GBC 1845 V',
    driverName: 'Farhan bin Mansor',
    driverContact: '+65 9555 6677',
    uraArea: 'Sembawang',
    gpsLocation: { x: 500, y: 140, lat: 1.4491, lng: 103.8185 },
    deliveries: [
      {
        id: 'del-25-01',
        item: 'Naval Vessel Electrical Harnesses',
        pickupLocation: 'Sembawang Wharves Gate 2',
        dropoffLocation: 'Sun Plaza Retail Receiving Bay',
        pickupUra: 'Sembawang',
        dropoffUra: 'Sembawang',
        estimatedTime: '14:15 - 14:45',
        estimatedDistance: '3.3 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-25-02',
        item: 'Cold Storage Frozen Seafood Crates',
        pickupLocation: 'Admiralty Road West Cold Store',
        dropoffLocation: 'Sembawang Mart Supermarket Bay',
        pickupUra: 'Sembawang',
        dropoffUra: 'Sembawang',
        estimatedTime: '15:20 - 15:50',
        estimatedDistance: '2.9 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-26',
    managerId: 'mgr-3',
    carPlate: 'SLA 9021 W',
    driverName: 'Wong Kah Fatt',
    driverContact: '+65 8666 7788',
    uraArea: 'Yishun',
    gpsLocation: { x: 540, y: 180, lat: 1.4304, lng: 103.8354 },
    deliveries: [
      {
        id: 'del-26-01',
        item: 'Biomedical Diagnostic Test Reagents',
        pickupLocation: 'Yishun Industrial Park A Block 1020',
        dropoffLocation: 'Khoo Teck Puat Hospital Stores Wing',
        pickupUra: 'Yishun',
        dropoffUra: 'Yishun',
        estimatedTime: '14:05 - 14:35',
        estimatedDistance: '3.1 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-26-02',
        item: 'Commercial LED Architectural Lighting',
        pickupLocation: 'Northpoint City South Wing',
        dropoffLocation: 'Yishun Avenue 7 Distribution Centre',
        pickupUra: 'Yishun',
        dropoffUra: 'Yishun',
        estimatedTime: '15:15 - 15:45',
        estimatedDistance: '3.8 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-27',
    managerId: 'mgr-3',
    carPlate: 'GBF 5580 X',
    driverName: 'Siti Rahmah bte Ismail',
    driverContact: '+65 9777 8899',
    uraArea: 'Bukit Batok',
    gpsLocation: { x: 390, y: 340, lat: 1.3590, lng: 103.7540 },
    deliveries: [
      {
        id: 'del-27-01',
        item: 'Building Acoustics Insulation Panels',
        pickupLocation: 'Bukit Batok Industrial Park A St 33',
        dropoffLocation: 'West Mall Loading Bay 2',
        pickupUra: 'Bukit Batok',
        dropoffUra: 'Bukit Batok',
        estimatedTime: '14:20 - 14:50',
        estimatedDistance: '2.7 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-27-02',
        item: 'Heavy Duty Power Inverter Banks',
        pickupLocation: 'Hillview Terrace Light Industrial',
        dropoffLocation: 'Bukit Gombak Stadium Logistics Post',
        pickupUra: 'Bukit Batok',
        dropoffUra: 'Bukit Batok',
        estimatedTime: '15:30 - 16:00',
        estimatedDistance: '3.4 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-28',
    managerId: 'mgr-3',
    carPlate: 'SKT 4301 Y',
    driverName: 'Kelvin Ng Soon Huat',
    driverContact: '+65 8888 9900',
    uraArea: 'Choa Chu Kang',
    gpsLocation: { x: 360, y: 280, lat: 1.3840, lng: 103.7470 },
    deliveries: [
      {
        id: 'del-28-01',
        item: 'Organic Urban Farm Fresh Greens',
        pickupLocation: 'Murai Farmway Agri-Hub Block 4',
        dropoffLocation: 'Lot One Shoppers\' Mall Loading Bay',
        pickupUra: 'Choa Chu Kang',
        dropoffUra: 'Choa Chu Kang',
        estimatedTime: '14:10 - 14:40',
        estimatedDistance: '4.8 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
    ],
  },
  {
    id: 'veh-29',
    managerId: 'mgr-3',
    carPlate: 'GBC 6729 Z',
    driverName: 'Praveen Raj',
    driverContact: '+65 9999 0011',
    uraArea: 'Bukit Panjang',
    gpsLocation: { x: 420, y: 270, lat: 1.3774, lng: 103.7719 },
    deliveries: [
      {
        id: 'del-29-01',
        item: 'Cleanroom Sterile Filter Elements',
        pickupLocation: 'Senja Link Commercial Centre',
        dropoffLocation: 'Hillion Mall Basement Logistics Hub',
        pickupUra: 'Bukit Panjang',
        dropoffUra: 'Bukit Panjang',
        estimatedTime: '14:15 - 14:45',
        estimatedDistance: '2.3 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-29-02',
        item: 'Security CCTV Server Storage Arrays',
        pickupLocation: 'Petir Road Telecom Exchange',
        dropoffLocation: 'Fajar Shopping Centre Admin Office',
        pickupUra: 'Bukit Panjang',
        dropoffUra: 'Bukit Panjang',
        estimatedTime: '15:20 - 15:50',
        estimatedDistance: '2.9 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
  {
    id: 'veh-30',
    managerId: 'mgr-3',
    carPlate: 'SGB 1109 A',
    driverName: 'Raymond Chan Wai Keong',
    driverContact: '+65 8000 1122',
    uraArea: 'Clementi',
    gpsLocation: { x: 410, y: 420, lat: 1.3162, lng: 103.7649 },
    deliveries: [
      {
        id: 'del-30-01',
        item: 'Educational Robotics Controller Kits',
        pickupLocation: 'Clementi Loop Logistics Warehouse 12',
        dropoffLocation: 'Singapore Polytechnic Engineering Dept',
        pickupUra: 'Clementi',
        dropoffUra: 'Clementi',
        estimatedTime: '14:00 - 14:30',
        estimatedDistance: '3.6 km',
        status: 'in_transit',
        isDelayed: false,
        isInTransit: true,
        sequence: 1,
      },
      {
        id: 'del-30-02',
        item: 'Scientific Micro-Pipettes and Glassware',
        pickupLocation: 'West Coast Highway Distribution Hub',
        dropoffLocation: 'The Clementi Mall Delivery Receiving Bay',
        pickupUra: 'Clementi',
        dropoffUra: 'Clementi',
        estimatedTime: '15:00 - 15:30',
        estimatedDistance: '2.8 km',
        status: 'scheduled',
        isDelayed: false,
        sequence: 2,
      },
    ],
  },
];

// Realistic Singapore URA Areas with SVG path coordinates matching the island silhouette (viewBox: 0 0 1000 620)
export const URA_AREAS: UraAreaBoundary[] = [
  // West Region
  {
    id: 'tuas',
    name: 'Tuas',
    region: 'West',
    path: 'M 90,450 L 160,390 L 220,410 L 210,480 L 140,540 L 70,510 Z',
    center: { x: 150, y: 460 },
  },
  {
    id: 'pioneer',
    name: 'Pioneer & Jurong Ind.',
    region: 'West',
    path: 'M 220,410 L 290,380 L 320,430 L 270,490 L 210,480 Z',
    center: { x: 260, y: 440 },
  },
  {
    id: 'jurong_west',
    name: 'Jurong West & NTU',
    region: 'West',
    path: 'M 220,340 L 310,320 L 320,380 L 250,400 L 220,370 Z',
    center: { x: 270, y: 360 },
  },
  {
    id: 'jurong_east',
    name: 'Jurong East',
    region: 'West',
    path: 'M 320,340 L 380,340 L 400,410 L 330,420 L 320,380 Z',
    center: { x: 360, y: 380 },
  },
  {
    id: 'clementi',
    name: 'Clementi',
    region: 'West',
    path: 'M 380,360 L 430,360 L 440,440 L 390,440 L 380,390 Z',
    center: { x: 410, y: 400 },
  },
  {
    id: 'bukit_batok',
    name: 'Bukit Batok',
    region: 'West',
    path: 'M 330,290 L 400,290 L 410,360 L 340,360 Z',
    center: { x: 370, y: 325 },
  },
  {
    id: 'choa_chu_kang',
    name: 'Choa Chu Kang',
    region: 'West',
    path: 'M 270,240 L 380,230 L 370,290 L 300,300 Z',
    center: { x: 330, y: 265 },
  },
  {
    id: 'bukit_panjang',
    name: 'Bukit Panjang',
    region: 'West',
    path: 'M 380,230 L 440,240 L 440,310 L 380,290 Z',
    center: { x: 410, y: 270 },
  },
  {
    id: 'western_islands',
    name: 'Jurong Island (Western Is.)',
    region: 'West',
    path: 'M 220,510 L 320,490 L 340,540 L 250,565 Z',
    center: { x: 280, y: 530 },
  },

  // North Region
  {
    id: 'lim_chu_kang',
    name: 'Lim Chu Kang & Catchment',
    region: 'North',
    path: 'M 260,180 L 360,170 L 350,240 L 240,240 Z',
    center: { x: 300, y: 200 },
  },
  {
    id: 'woodlands',
    name: 'Woodlands',
    region: 'North',
    path: 'M 360,120 L 460,120 L 460,190 L 360,190 Z',
    center: { x: 410, y: 155 },
  },
  {
    id: 'sembawang',
    name: 'Sembawang',
    region: 'North',
    path: 'M 460,110 L 530,120 L 530,190 L 460,190 Z',
    center: { x: 495, y: 150 },
  },
  {
    id: 'mandai',
    name: 'Mandai & Central Catchment',
    region: 'North',
    path: 'M 370,190 L 490,190 L 480,260 L 370,260 Z',
    center: { x: 430, y: 225 },
  },
  {
    id: 'yishun',
    name: 'Yishun',
    region: 'North',
    path: 'M 510,150 L 580,150 L 580,220 L 500,220 Z',
    center: { x: 545, y: 185 },
  },

  // North-East Region
  {
    id: 'seletar',
    name: 'Seletar Aerospace',
    region: 'North-East',
    path: 'M 570,140 L 650,150 L 640,210 L 570,200 Z',
    center: { x: 605, y: 175 },
  },
  {
    id: 'punggol',
    name: 'Punggol',
    region: 'North-East',
    path: 'M 640,150 L 710,160 L 700,225 L 630,220 Z',
    center: { x: 670, y: 190 },
  },
  {
    id: 'sengkang',
    name: 'Sengkang',
    region: 'North-East',
    path: 'M 620,220 L 690,225 L 680,270 L 610,265 Z',
    center: { x: 650, y: 245 },
  },
  {
    id: 'hougang',
    name: 'Hougang',
    region: 'North-East',
    path: 'M 600,265 L 670,270 L 660,320 L 590,315 Z',
    center: { x: 630, y: 290 },
  },
  {
    id: 'ang_mo_kio',
    name: 'Ang Mo Kio',
    region: 'North-East',
    path: 'M 510,230 L 590,230 L 580,300 L 510,290 Z',
    center: { x: 550, y: 265 },
  },
  {
    id: 'serangoon',
    name: 'Serangoon',
    region: 'North-East',
    path: 'M 560,295 L 630,300 L 620,350 L 560,345 Z',
    center: { x: 595, y: 320 },
  },

  // East Region
  {
    id: 'pasir_ris',
    name: 'Pasir Ris',
    region: 'East',
    path: 'M 710,200 L 800,220 L 790,285 L 700,270 Z',
    center: { x: 750, y: 245 },
  },
  {
    id: 'tampines',
    name: 'Tampines',
    region: 'East',
    path: 'M 680,275 L 770,285 L 765,360 L 675,345 Z',
    center: { x: 725, y: 315 },
  },
  {
    id: 'changi',
    name: 'Changi Airport & Aviation',
    region: 'East',
    path: 'M 780,250 L 880,280 L 860,400 L 775,370 L 780,290 Z',
    center: { x: 825, y: 330 },
  },
  {
    id: 'bedok',
    name: 'Bedok',
    region: 'East',
    path: 'M 630,335 L 720,350 L 710,410 L 625,395 Z',
    center: { x: 670, y: 375 },
  },
  {
    id: 'paya_lebar',
    name: 'Paya Lebar',
    region: 'East',
    path: 'M 605,335 L 660,340 L 650,380 L 595,375 Z',
    center: { x: 625, y: 360 },
  },

  // Central Region
  {
    id: 'bishan',
    name: 'Bishan',
    region: 'Central',
    path: 'M 500,290 L 560,295 L 550,340 L 490,335 Z',
    center: { x: 525, y: 315 },
  },
  {
    id: 'toa_payoh',
    name: 'Toa Payoh',
    region: 'Central',
    path: 'M 510,335 L 580,340 L 570,385 L 505,380 Z',
    center: { x: 540, y: 360 },
  },
  {
    id: 'novena',
    name: 'Novena & Newton',
    region: 'Central',
    path: 'M 500,380 L 560,385 L 550,420 L 490,415 Z',
    center: { x: 525, y: 400 },
  },
  {
    id: 'kallang',
    name: 'Kallang & Geylang',
    region: 'Central',
    path: 'M 565,375 L 635,380 L 625,430 L 560,425 Z',
    center: { x: 595, y: 400 },
  },
  {
    id: 'marine_parade',
    name: 'Marine Parade & East Coast',
    region: 'Central',
    path: 'M 610,425 L 700,415 L 710,450 L 610,455 Z',
    center: { x: 660, y: 435 },
  },
  {
    id: 'bukit_timah',
    name: 'Bukit Timah',
    region: 'Central',
    path: 'M 430,310 L 495,310 L 485,385 L 420,385 Z',
    center: { x: 460, y: 350 },
  },
  {
    id: 'tanglin',
    name: 'Tanglin & Orchard',
    region: 'Central',
    path: 'M 460,385 L 525,385 L 520,430 L 450,430 Z',
    center: { x: 490, y: 410 },
  },
  {
    id: 'downtown_core',
    name: 'Downtown Core & Marina Bay',
    region: 'Central',
    path: 'M 525,420 L 585,420 L 575,475 L 515,470 Z',
    center: { x: 550, y: 445 },
  },
  {
    id: 'bukit_merah',
    name: 'Bukit Merah',
    region: 'Central',
    path: 'M 465,430 L 530,435 L 520,490 L 450,480 Z',
    center: { x: 490, y: 460 },
  },
  {
    id: 'queenstown',
    name: 'Queenstown & Pasir Panjang',
    region: 'Central',
    path: 'M 420,430 L 475,435 L 460,500 L 400,490 Z',
    center: { x: 440, y: 465 },
  },
  {
    id: 'sentosa',
    name: 'Sentosa & Southern Islands',
    region: 'Central',
    path: 'M 470,520 L 530,510 L 550,540 L 480,550 Z',
    center: { x: 510, y: 530 },
  },
];
